// Static metadata for recommendation engine
// Maps each exercise ID to recommendation-relevant attributes

export const EXERCISE_METADATA = {
    a1: { // Shoulder Shrugs
        targetImpairments: ['motor'],
        bodyRegion: 'upper',
        bilateral: true,
        safeForSevere: true,
        phaseRelevance: { acute: 3, subacute: 2, chronic: 1 },
    },
    a2: { // Table Push
        targetImpairments: ['motor'],
        bodyRegion: 'upper',
        bilateral: false,
        safeForSevere: true,
        phaseRelevance: { acute: 2, subacute: 3, chronic: 2 },
    },
    a3: { // Bicep Curls
        targetImpairments: ['motor'],
        bodyRegion: 'upper',
        bilateral: false,
        safeForSevere: false,
        phaseRelevance: { acute: 0, subacute: 2, chronic: 3 },
    },
    l1: { // Ankle Pumps
        targetImpairments: ['motor'],
        bodyRegion: 'lower',
        bilateral: true,
        safeForSevere: true,
        phaseRelevance: { acute: 3, subacute: 2, chronic: 1 },
    },
    l2: { // Seated Marching
        targetImpairments: ['motor'],
        bodyRegion: 'lower',
        bilateral: true,
        safeForSevere: true,
        phaseRelevance: { acute: 2, subacute: 3, chronic: 2 },
    },
    l3: { // Sit-to-Stand
        targetImpairments: ['motor'],
        bodyRegion: 'lower',
        bilateral: true,
        safeForSevere: false,
        phaseRelevance: { acute: 0, subacute: 2, chronic: 3 },
    },
    c1: { // Trunk Rotations
        targetImpairments: ['motor'],
        bodyRegion: 'core',
        bilateral: true,
        safeForSevere: true,
        phaseRelevance: { acute: 2, subacute: 3, chronic: 2 },
    },
    c2: { // Lateral Flexion
        targetImpairments: ['motor'],
        bodyRegion: 'core',
        bilateral: true,
        safeForSevere: true,
        phaseRelevance: { acute: 1, subacute: 3, chronic: 2 },
    },
    c3: { // Seated Balance
        targetImpairments: ['motor', 'cognitive'],
        bodyRegion: 'core',
        bilateral: true,
        safeForSevere: false,
        phaseRelevance: { acute: 0, subacute: 2, chronic: 3 },
    },
    h1: { // Fist Clenches
        targetImpairments: ['motor'],
        bodyRegion: 'fine_motor',
        bilateral: false,
        safeForSevere: true,
        phaseRelevance: { acute: 3, subacute: 3, chronic: 2 },
    },
    h2: { // Towel Scrunch
        targetImpairments: ['motor'],
        bodyRegion: 'fine_motor',
        bilateral: false,
        safeForSevere: false,
        phaseRelevance: { acute: 1, subacute: 3, chronic: 2 },
    },
    h3: { // Thumb Touch
        targetImpairments: ['motor', 'cognitive'],
        bodyRegion: 'fine_motor',
        bilateral: false,
        safeForSevere: false,
        phaseRelevance: { acute: 0, subacute: 2, chronic: 3 },
    },
    // Head & Neck
    n1: { targetImpairments: ['motor'], bodyRegion: 'head_neck', bilateral: true, safeForSevere: true, phaseRelevance: { acute: 2, subacute: 3, chronic: 2 } },
    n2: { targetImpairments: ['motor'], bodyRegion: 'head_neck', bilateral: true, safeForSevere: true, phaseRelevance: { acute: 2, subacute: 3, chronic: 2 } },
    n3: { targetImpairments: ['motor'], bodyRegion: 'head_neck', bilateral: true, safeForSevere: false, phaseRelevance: { acute: 1, subacute: 2, chronic: 3 } },
    n4: { targetImpairments: ['motor'], bodyRegion: 'head_neck', bilateral: true, safeForSevere: false, phaseRelevance: { acute: 1, subacute: 2, chronic: 3 } },
    n5: { targetImpairments: ['motor'], bodyRegion: 'head_neck', bilateral: true, safeForSevere: true, phaseRelevance: { acute: 2, subacute: 3, chronic: 2 } },
    n6: { targetImpairments: ['motor'], bodyRegion: 'head_neck', bilateral: true, safeForSevere: true, phaseRelevance: { acute: 2, subacute: 3, chronic: 2 } },
    n7: { targetImpairments: ['motor'], bodyRegion: 'head_neck', bilateral: true, safeForSevere: true, phaseRelevance: { acute: 2, subacute: 3, chronic: 2 } },
    // Arms (continued)
    a4: { targetImpairments: ['motor'], bodyRegion: 'upper', bilateral: false, safeForSevere: true, phaseRelevance: { acute: 2, subacute: 3, chronic: 2 } },
    a5: { targetImpairments: ['motor'], bodyRegion: 'upper', bilateral: false, safeForSevere: true, phaseRelevance: { acute: 2, subacute: 3, chronic: 2 } },
    a6: { targetImpairments: ['motor'], bodyRegion: 'upper', bilateral: false, safeForSevere: true, phaseRelevance: { acute: 2, subacute: 3, chronic: 2 } },
    a7: { targetImpairments: ['motor'], bodyRegion: 'upper', bilateral: false, safeForSevere: true, phaseRelevance: { acute: 2, subacute: 3, chronic: 2 } },
    a8: { targetImpairments: ['motor'], bodyRegion: 'upper', bilateral: true, safeForSevere: true, phaseRelevance: { acute: 2, subacute: 3, chronic: 2 } },
    a9: { targetImpairments: ['motor'], bodyRegion: 'upper', bilateral: true, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 2, chronic: 3 } },
    a10: { targetImpairments: ['motor'], bodyRegion: 'upper', bilateral: false, safeForSevere: true, phaseRelevance: { acute: 2, subacute: 3, chronic: 2 } },
    a11: { targetImpairments: ['motor'], bodyRegion: 'upper', bilateral: false, safeForSevere: true, phaseRelevance: { acute: 2, subacute: 3, chronic: 2 } },
    a12: { targetImpairments: ['motor'], bodyRegion: 'upper', bilateral: false, safeForSevere: true, phaseRelevance: { acute: 2, subacute: 3, chronic: 2 } },
    a13: { targetImpairments: ['motor'], bodyRegion: 'upper', bilateral: true, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 2, chronic: 3 } },
    a14: { targetImpairments: ['motor'], bodyRegion: 'upper', bilateral: false, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 2, chronic: 3 } },
    a15: { targetImpairments: ['motor'], bodyRegion: 'upper', bilateral: false, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 2, chronic: 3 } },
    a16: { targetImpairments: ['motor'], bodyRegion: 'upper', bilateral: true, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 2, chronic: 3 } },
    // Legs (continued)
    l4: { targetImpairments: ['motor'], bodyRegion: 'lower', bilateral: false, safeForSevere: true, phaseRelevance: { acute: 2, subacute: 3, chronic: 2 } },
    l5: { targetImpairments: ['motor'], bodyRegion: 'lower', bilateral: true, safeForSevere: true, phaseRelevance: { acute: 2, subacute: 3, chronic: 2 } },
    l6: { targetImpairments: ['motor'], bodyRegion: 'lower', bilateral: true, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 2, chronic: 3 } },
    l7: { targetImpairments: ['motor'], bodyRegion: 'lower', bilateral: true, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 2, chronic: 3 } },
    l8: { targetImpairments: ['motor'], bodyRegion: 'lower', bilateral: false, safeForSevere: true, phaseRelevance: { acute: 3, subacute: 2, chronic: 1 } },
    l9: { targetImpairments: ['motor'], bodyRegion: 'lower', bilateral: false, safeForSevere: true, phaseRelevance: { acute: 2, subacute: 3, chronic: 2 } },
    l10: { targetImpairments: ['motor'], bodyRegion: 'lower', bilateral: true, safeForSevere: true, phaseRelevance: { acute: 1, subacute: 3, chronic: 2 } },
    l11: { targetImpairments: ['motor'], bodyRegion: 'lower', bilateral: false, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 2, chronic: 3 } },
    l12: { targetImpairments: ['motor'], bodyRegion: 'lower', bilateral: false, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 2, chronic: 3 } },
    l13: { targetImpairments: ['motor'], bodyRegion: 'lower', bilateral: false, safeForSevere: true, phaseRelevance: { acute: 2, subacute: 3, chronic: 2 } },
    l14: { targetImpairments: ['motor'], bodyRegion: 'lower', bilateral: false, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 2, chronic: 3 } },
    l15: { targetImpairments: ['motor'], bodyRegion: 'lower', bilateral: false, safeForSevere: true, phaseRelevance: { acute: 1, subacute: 3, chronic: 2 } },
    l16: { targetImpairments: ['motor'], bodyRegion: 'lower', bilateral: true, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 2, chronic: 3 } },
    l17: { targetImpairments: ['motor'], bodyRegion: 'lower', bilateral: false, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 1, chronic: 3 } },
    l18: { targetImpairments: ['motor'], bodyRegion: 'lower', bilateral: false, safeForSevere: true, phaseRelevance: { acute: 1, subacute: 3, chronic: 2 } },
    l19: { targetImpairments: ['motor'], bodyRegion: 'lower', bilateral: false, safeForSevere: true, phaseRelevance: { acute: 1, subacute: 3, chronic: 2 } },
    l20: { targetImpairments: ['motor'], bodyRegion: 'lower', bilateral: true, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 2, chronic: 3 } },
    l21: { targetImpairments: ['motor'], bodyRegion: 'lower', bilateral: true, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 2, chronic: 3 } },
    l22: { targetImpairments: ['motor'], bodyRegion: 'lower', bilateral: true, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 2, chronic: 3 } },
    l23: { targetImpairments: ['motor'], bodyRegion: 'lower', bilateral: true, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 2, chronic: 3 } },
    l24: { targetImpairments: ['motor'], bodyRegion: 'lower', bilateral: true, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 1, chronic: 3 } },
    // Core (continued)
    c4: { targetImpairments: ['motor'], bodyRegion: 'core', bilateral: true, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 2, chronic: 3 } },
    c5: { targetImpairments: ['motor'], bodyRegion: 'core', bilateral: false, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 2, chronic: 3 } },
    c6: { targetImpairments: ['motor'], bodyRegion: 'core', bilateral: false, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 1, chronic: 3 } },
    c7: { targetImpairments: ['motor'], bodyRegion: 'core', bilateral: true, safeForSevere: true, phaseRelevance: { acute: 2, subacute: 3, chronic: 2 } },
    c8: { targetImpairments: ['motor'], bodyRegion: 'core', bilateral: true, safeForSevere: true, phaseRelevance: { acute: 2, subacute: 3, chronic: 2 } },
    c9: { targetImpairments: ['motor'], bodyRegion: 'core', bilateral: true, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 2, chronic: 3 } },
    c10: { targetImpairments: ['motor', 'cognitive'], bodyRegion: 'core', bilateral: true, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 2, chronic: 3 } },
    c11: { targetImpairments: ['motor', 'cognitive'], bodyRegion: 'core', bilateral: false, safeForSevere: false, phaseRelevance: { acute: 0, subacute: 2, chronic: 3 } },
    c12: { targetImpairments: ['motor'], bodyRegion: 'core', bilateral: true, safeForSevere: true, phaseRelevance: { acute: 2, subacute: 3, chronic: 2 } },
};

// Human-readable reason strings for each body region
export const REGION_REASONS = {
    upper: 'For upper body recovery',
    lower: 'For lower body mobility',
    core: 'For core stability',
    fine_motor: 'For fine motor skills',
    head_neck: 'For jaw and cervical recovery',
};
