require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

def ccache_enabled?(podfile_properties)
  # Environment variable takes precedence
  return ENV['USE_CCACHE'] == '1' if ENV['USE_CCACHE']
  
  # Fall back to Podfile properties
  podfile_properties['apple.ccacheEnabled'] == 'true'
end

ENV['RCT_NEW_ARCH_ENABLED'] ||= '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] ||= podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
ENV['RCT_USE_RN_DEP'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'

prepare_react_native_project!

target 'NeuroBloom' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'npx',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => ccache_enabled?(podfile_properties),
    )
    
    # Suppress nullability warnings from dependencies
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
        config.build_settings['CLANG_WARN_UNGUARDED_AVAILABILITY'] = 'NO'
        # Suppress nullability warnings
        config.build_settings['CLANG_WARN_NULLABILITY'] = 'NO'
        # Suppress deprecation warnings
        config.build_settings['GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS'] = 'NO'
        # Add compiler flags to suppress nullability warnings
        if config.build_settings['OTHER_CFLAGS']
          config.build_settings['OTHER_CFLAGS'] << '-Wno-nullability-completeness'
        else
          config.build_settings['OTHER_CFLAGS'] = ['-Wno-nullability-completeness']
        end
      end
    end
    
    # Suppress warnings for problematic pods (including ExpoModulesCore)
    installer.pods_project.targets.each do |target|
      if ['ExpoModulesCore', 'ExpoFileSystem', 'EXAV', 'ExpoAudio'].include?(target.name)
        target.build_configurations.each do |config|
          config.build_settings['CLANG_WARN_NULLABILITY'] = 'NO'
          config.build_settings['GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS'] = 'NO'
          # Add compiler flags
          if config.build_settings['OTHER_CFLAGS']
            config.build_settings['OTHER_CFLAGS'] << '-Wno-nullability-completeness'
          else
            config.build_settings['OTHER_CFLAGS'] = ['-Wno-nullability-completeness']
          end
        end
      end
    end
    
    # Add warning flags to suppress nullability warnings via compiler flags
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Use WARNING_CFLAGS to suppress nullability warnings
        warning_flags = config.build_settings['WARNING_CFLAGS'] || ['$(inherited)']
        warning_flags << '-Wno-nullability-completeness' unless warning_flags.include?('-Wno-nullability-completeness')
        config.build_settings['WARNING_CFLAGS'] = warning_flags
      end
    end
  end
end
